- name: Configure EC2
  hosts: web
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes
