# Tocreate
ansible-vault create secrets.yml
#inside the vault page
db_user: admin
db_pass: SuperSecret123

#to access the secrets
ansible-vault view secrets.yml

#to edit
ansible-vault edit secrets.yml

# playbook.yml
- name: Use secret variables
  hosts: db_servers
  vars_files:
    - secrets.yml
  tasks:
    - name: Print DB credentials
      debug:
        msg: "User is {{ db_user }} and password is {{ db_pass }}"
