- name: DBServer setup
  hosts: dbservers
  become: yes
  vars:
    dbuser: current
    dbpass: tesla
    dbname: Electric
  tasks:
    - debug:
       msg: "The DB name is {{dbname}}"

    - debug:
       var: dbuser

    - name: Install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

          #installing dependency
    - name: Install python3-pymysql
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present

    - name: Start and enable maria service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name 'bobdata'
      community.mysql.mysql_db:
        name: "{{dbname}}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create ddatabase user with name 'vprofile'
      community.mysql.mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
      register: dbout

     - name: Print the dbout variable to show the logs
       debug:
         var: dbout

